const userPath = (path: string): string => `/users/${path}`;

export const Api = {
  SIGN_IN: userPath('google'),
  SIGN_OUT: userPath('signout'),
  BANNERS: userPath('banners'),
  GET_BY_ID: userPath(''),
};

export const REPONSE_CONSTANT = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL: 'GET_USER_BY_ID_FAIL',
  FOR_GOT_PW_SUCCESS: 'FOR_GOT_PW_SUCCESS',
  FOR_GOT_PW_FAIL: 'FOR_GOT_PW_FAIL',
  RESEND_ORDER_RESET_PASSWORD_SUCCESS: 'RESEND_ORDER_RESET_PASSWORD_SUCCESS',
  RESEND_ORDER_RESET_PASSWORD_FAIL: 'RESEND_ORDER_RESET_PASSWORD_FAIL',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
  REGISTER_OWNER_SHOP_SUCCESS: 'REGISTER_OWNER_SHOP_SUCCESS',
  REGISTER_OWNER_SHOP_FAIL: 'REGISTER_OWNER_SHOP_FAIL',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAIL: 'UPLOAD_FILE_FAIL',
};
